<template>
    <component :is="iconComponent" :size="size" :class="iconClass" />
</template>

<script setup>
import { computed } from "vue";
import {
    Home,
    UserCircle,
    Map,
    FileText,
    Signal,
    Archive,
    Building,
    DollarSign,
    RotateCcw,
    CreditCard,
    Ticket,
    Users,
    ChevronDown,
    LogOut,
    Settings,
    Bell,
    Trash2,
    Pencil,
    Plus,
    MessageCircle,
    Download,
    EyeOff,
    Eye,
    RefreshCw,
    RotateCw,
    Edit,
    Printer,
    EllipsisVertical,
    X,
    Phone,
    Calendar,
    MapPin,
    Tag,
    Navigation,
    Building2,
    User,
    Check,
    Info,
    Wifi,
    Handshake,
    Wallet,
    TrendingUp,
    TrendingDown,
    Briefcase,
    ArrowUp,
    ArrowDown,
    Star,
    Server,
    Bolt,
    Camera,
    AlertTriangle,
    Power,
    CheckCircle,
    ArrowLeft,
    Wrench,
    Upload,
    Key,
    Lock,
    Network,
    Activity,
    Clock,
    Flag,
    Mail,
    Package,
    Search,
    Image,
    ShoppingBag,
    Globe,
    Monitor,
    SquarePen,
    ExternalLink,
    ChartBar,
    Box,
} from "lucide-vue-next";

const props = defineProps({
    name: {
        type: String,
        required: true,
    },
    size: {
        type: [String, Number],
        default: 20,
    },
    class: {
        type: String,
        default: "",
    },
});

const iconClass = computed(() => props.class);

const iconMap = {
    home: Home,
    "user-circle": UserCircle,
    map: Map,
    "document-text": FileText,
    signal: Signal,
    "archive-box": Archive,
    "building-office": Building,
    "currency-dollar": DollarSign,
    "arrow-path": RotateCcw,
    "credit-card": CreditCard,
    ticket: Ticket,
    users: Users,
    "chevron-down": ChevronDown,
    "log-out": LogOut,
    settings: Settings,
    bell: Bell,
    trash: Trash2,
    "trash-2": Trash2,
    pencil: Pencil,
    plus: Plus,
    "message-circle": MessageCircle,
    download: Download,
    "eye-off": EyeOff,
    eye: Eye,
    "refresh-cw": RefreshCw,
    "rotate-cw": RotateCw,
    edit: Edit,
    printer: Printer,
    "ellipsis-vertical": EllipsisVertical,
    x: X,
    phone: Phone,
    calendar: Calendar,
    "map-pin": MapPin,
    tag: Tag,
    navigation: Navigation,
    "building-2": Building2,
    user: User,
    check: Check,
    info: Info,
    wifi: Wifi,
    handshake: Handshake,
    wallet: Wallet,
    "trending-up": TrendingUp,
    "trending-down": TrendingDown,
    briefcase: Briefcase,
    "arrow-up": ArrowUp,
    "arrow-down": ArrowDown,
    star: Star,
    server: Server,
    "server-stack": Server,
    bolt: Bolt,
    camera: Camera,
    "alert-triangle": AlertTriangle,
    power: Power,
    "check-circle": CheckCircle,
    "arrow-left": ArrowLeft,
    wrench: Wrench,
    upload: Upload,
    key: Key,
    lock: Lock,
    network: Network,
    cable: Network,
    activity: Activity,
    clock: Clock,
    flag: Flag,
    mail: Mail,
    package: Package,
    "cpu-chip": Server,
    "file-check": CheckCircle,
    "x-circle": X,
    "plus-circle": Plus,
    "user-group": Users,
    "settings-6-tooth": Settings,
    "search-plus": Search,
    photo: Image,
    file: FileText,
    "shopping-bag": ShoppingBag,
    "globe-alt": Globe,
    "computer-desktop": Monitor,
    "calendar-days": Calendar,
    "pencil-square": SquarePen,
    "arrow-top-right-on-square": ExternalLink,
    "list-bullet": FileText,
    building: Building,
    "file-plus": Plus,
    "bar-chart": ChartBar,
    cube: Box,
    "wrench-screwdriver": Wrench,
};

const iconComponent = computed(() => {
    return iconMap[props.name] || Home; // fallback to Home icon
});
</script>
